name: textly_posts
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  dart_jsonwebtoken: ^2.4.2
  dotenv: ^4.1.0
  logger: ^1.2.2
  postgres: ^2.6.1
  textly_core:
    git:
      url: git@github.com:serezhia/textly_core.git
      ref: dev
  uuid: ^3.0.7

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
